Revert to old release version calling bzr - this one is currently set (it checks if the tag exists and exit on error - there are API change in bzr: set_parent_branch is set_parent now - the new version doesn't pull before pushing - it spawns an error I couldn't catch when calling target_dir =   BzrDir.open(branch_location) (Exception AttributeError: "'NoneType' object has no attribute 'close'" in <bound method SmartSSHClientMedium.__del__ of SmartSSHClientMedium(bzr+ssh://didrocks@bazaar.launchpad.net/)> ignored Exception AttributeError: "'NoneType' object has no attribute 'close'" in <function terminate at 0x9bedf44> ignored )
This should be fix for next Quickly release